name: CI

on:
  push:
    branches: [ main ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
      # env:
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - uses: actions/checkout@v4
      - name: Check for dockerenv file
        run: |
          ls /.dockerenv && echo Found dockerenv
          echo "No dockerenv"
      - name: Compiler hello.chpl
        run: |
          chpl hello.chpl
      - name: Run hello.chpl
        run: |
          ./hello
